name: dependencies
description: A new Flutter project.
version: 0.0.1

publish_to: "none"

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  get_storage: ^2.0.2
#  flutter_localization: ^0.1.10
  easy_localization: ^3.0.2
  dio: ^4.0.0
  internet_connection_checker: ^1.0.0+1
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.0+1
  lottie: ^2.2.0
  bottom_picker: ^2.0.1
  intl: ^0.18.0
  dotted_border: ^2.0.0+3
  pin_code_fields: ^7.4.0
  slider_controller: ^0.0.4
  sleek_circular_slider: ^2.0.1
  cupertino_tabbar: ^2.0.0
  flutter_calendar_carousel:
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  rxdart: ^0.27.7
  introduction_screen: ^3.1.4
  image_picker: ^0.8.6+1
  mockito: ^5.3.2
  flutter_staggered_animations: ^1.1.1
  flutter_switch: ^0.3.2
  popover: ^0.2.8+1
  socket_io_client: ^2.0.1
#  image_downloader: ^0.31.0
  sip_ua: 0.5.8
  permission_handler: ^10.2.0
  cached_network_image: ^3.2.3
  social_media_recorder: ^0.1.86
  voice_message_package: ^1.0.41
  google_maps_flutter: ^2.2.5
  youtube_player_flutter: 8.1.2
  flutter_inappwebview: ^5.7.2+3
  path_provider: ^2.0.14
  sqflite: ^2.2.6
  scrollable_positioned_list: ^0.3.5
  carousel_indicator: ^1.0.6
  open_file: ^3.2.1
  url_launcher: ^6.1.10
  firebase_messaging: ^14.4.1
  flutter_local_notifications: ^14.0.0
#  image_gallery_saver: '^1.7.1'


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  intl: ^0.18.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - ../lang/en.json
    - ../lang/ar.json
    - ../assets/images/
    - ../assets/icons/
    - ../assets/fonts/


